### ISSUE TITLE
Update Suggestion

### ISSUE THREAD

**Issue by Genhain** [keighl/KTUVDemo#1]
I was also looking for a way to centre on cells in a form of paging, and came across your example which is lovely and works like a charm. There is one small issue though.

If you have bounces turned on and you pull far past the end of the content view in whichever for direction (left or right for me) the targetContent offset will jump to an incorrect calculated index.

I have not taken the time to discover why exactly this is, i have a general idea however i did come up with a solution and that is basically make it treat it like it has bounces turned off [here is the source](https://gist.github.com/Genhain/9f2de3a8219e474cbc0a)

I know this is quite old, but out of all the resources i came across your's was the most helpful in reaching the desired effect, if but for this one little hiccough. just thought this might help others

**Comment by keighl** [comment]
Hey @Genhain thanks for sharing! Perhaps open a pull request with left/right example?

**Comment by Genhain** [comment]
Sorry had a brain fart and didnt check mail, ill get on it sometime during the week. Do you also plan on updating the site? since that is where anyone will probably stumble first when looking for a solution.
